/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TableData } from "./TableData";
import { TableDataCountArgs } from "./TableDataCountArgs";
import { TableDataFindManyArgs } from "./TableDataFindManyArgs";
import { TableDataFindUniqueArgs } from "./TableDataFindUniqueArgs";
import { DeleteTableDataArgs } from "./DeleteTableDataArgs";
import { TableDataService } from "../tableData.service";
@graphql.Resolver(() => TableData)
export class TableDataResolverBase {
  constructor(protected readonly service: TableDataService) {}

  async _tableDataItemsMeta(
    @graphql.Args() args: TableDataCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TableData])
  async tableDataItems(
    @graphql.Args() args: TableDataFindManyArgs
  ): Promise<TableData[]> {
    return this.service.tableDataItems(args);
  }

  @graphql.Query(() => TableData, { nullable: true })
  async tableData(
    @graphql.Args() args: TableDataFindUniqueArgs
  ): Promise<TableData | null> {
    const result = await this.service.tableData(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TableData)
  async deleteTableData(
    @graphql.Args() args: DeleteTableDataArgs
  ): Promise<TableData | null> {
    try {
      return await this.service.deleteTableData(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
